// Auto-generated by build.ts from jsr:@std/assert. Do not edit manually.
// deno-lint-ignore-file no-explicit-any
declare module 'jsr:@std/assert' {
  function assertAlmostEquals(actual: number, expected: number, tolerance?: number, msg?: string): void;
  type ArrayLikeArg<T> = ArrayLike<T> & object;
  function assertArrayIncludes<T>(actual: ArrayLikeArg<T>, expected: ArrayLikeArg<T>, msg?: string): void;
  function assertEquals<T>(actual: T, expected: T, msg?: string): void;
  function assertExists<T>(actual: T, msg?: string): asserts actual is NonNullable;
  type Falsy = false | 0 | unknown | "" | null | undefined;
  function assertFalse(expr: unknown, _): asserts expr is Falsy;
  function assertGreaterOrEqual<T>(actual: T, expected: T, msg?: string): void;
  function assertGreater<T>(actual: T, expected: T, msg?: string): void;
  type AnyConstructor = (...args: any[]) => any;
  type GetConstructorType<T extends AnyConstructor> = InstanceType<T>;
  function assertInstanceOf<T extends (...args: any[]) => any>(actual: unknown, expectedType: T, _): asserts actual is InstanceType;
  function assertIsError<E extends Error>(error: unknown, ErrorClass?: (...args: any[]) => E, msgMatches?: string | RegExp, msg?: string): asserts error is E;
  function assertLessOrEqual<T>(actual: T, expected: T, msg?: string): void;
  function assertLess<T>(actual: T, expected: T, msg?: string): void;
  function assertMatch(actual: string, expected: RegExp, msg?: string): void;
  function assertNotEquals<T>(actual: T, expected: T, msg?: string): void;
  function assertNotInstanceOf<A, T>(actual: A, unexpectedType: (...args: any[]) => T, msg?: string): asserts actual is Exclude;
  function assertNotMatch(actual: string, expected: RegExp, msg?: string): void;
  function assertNotStrictEquals<T>(actual: T, expected: T, msg?: string): void;
  function assertObjectMatch(actual: Record<PropertyKey, any>, expected: Record<PropertyKey, unknown>, msg?: string): void;
  function assertRejects(fn: () => PromiseLike<unknown>, msg?: string): Promise<unknown>;
  function assertRejects<E extends Error>(fn: () => PromiseLike<unknown>, ErrorClass: (...args: any[]) => E, msgIncludes?: string, msg?: string): Promise<E>;
  function assertRejects<E extends Error>(fn: () => PromiseLike<unknown>, errorClassOrMsg?: ((...args: any[]) => E) | string, msgIncludesOrMsg?: string, msg?: string): Promise<E | Error | unknown>;
  function assertStrictEquals<T>(actual: unknown, expected: T, msg?: string): asserts actual is T;
  function assertStringIncludes(actual: string, expected: string, msg?: string): void;
  function assertThrows(fn: () => unknown, msg?: string): unknown;
  function assertThrows<E extends Error>(fn: () => unknown, ErrorClass: (...args: any[]) => E, msgIncludes?: string, msg?: string): E;
  function assertThrows<E extends Error>(fn: () => unknown, errorClassOrMsg?: ((...args: any[]) => E) | string, msgIncludesOrMsg?: string, msg?: string): E | Error | unknown;
  function assert(expr: unknown, _): asserts expr;
  class AssertionError extends Error {
    constructor(message: string, options?: ErrorOptions);
  }
  function equal(a: unknown, b: unknown): boolean;
  function fail(msg?: string): never;
  function unimplemented(msg?: string): never;
  function unreachable(msg?: string): never;
  export { assertAlmostEquals, ArrayLikeArg, assertArrayIncludes, assertEquals, assertExists, Falsy, assertFalse, assertGreaterOrEqual, assertGreater, AnyConstructor, GetConstructorType, assertInstanceOf, assertIsError, assertLessOrEqual, assertLess, assertMatch, assertNotEquals, assertNotInstanceOf, assertNotMatch, assertNotStrictEquals, assertObjectMatch, assertRejects, assertStrictEquals, assertStringIncludes, assertThrows, assert, AssertionError, equal, fail, unimplemented, unreachable };
}
