// Auto-generated by build.ts from jsr:@std/testing/bdd. Do not edit manually.
declare module 'jsr:@std/testing/bdd' {
  interface DescribeDefinition<T> {
    fn?: () => void | undefined;
    suite?: TestSuite<T>;
    beforeAll?: (() => void | Promise<void>) | (() => void | Promise<void>)[];
    afterAll?: (() => void | Promise<void>) | (() => void | Promise<void>)[];
    beforeEach?: (() => void | Promise<void>) | (() => void | Promise<void>)[];
    afterEach?: (() => void | Promise<void>) | (() => void | Promise<void>)[];
  }
  interface ItDefinition<T> {
    fn: (t: Deno.TestContext) => void | Promise<void>;
    suite?: TestSuite<T>;
  }
  interface TestSuite<T> {
    symbol: symbol;
  }
  type ItArgs<T> = [ItDefinition<T>] | [string, Omit<ItDefinition<T>, "name">] | [string, (t: Deno.TestContext) => void | Promise<void>] | [(t: Deno.TestContext) => void | Promise<void>] | [string, Omit<ItDefinition<T>, "fn" | "name">, (t: Deno.TestContext) => void | Promise<void>] | [Omit<ItDefinition<T>, "fn">, (t: Deno.TestContext) => void | Promise<void>] | [Omit<ItDefinition<T>, "fn" | "name">, (t: Deno.TestContext) => void | Promise<void>] | [TestSuite<T>, string, Omit<ItDefinition<T>, "name" | "suite">] | [TestSuite<T>, string, (t: Deno.TestContext) => void | Promise<void>] | [TestSuite<T>, (t: Deno.TestContext) => void | Promise<void>] | [TestSuite<T>, string, Omit<ItDefinition<T>, "fn" | "name" | "suite">, (t: Deno.TestContext) => void | Promise<void>] | [TestSuite<T>, Omit<ItDefinition<T>, "fn" | "suite">, (t: Deno.TestContext) => void | Promise<void>] | [TestSuite<T>, Omit<ItDefinition<T>, "fn" | "name" | "suite">, (t: Deno.TestContext) => void | Promise<void>];
  function it<T>(...args: ItArgs<T>): void;
  function test<T>(...args: ItArgs<T>): void;
  function beforeAll<T>(fn: () => void | Promise<void>): void;
  function before<T>(fn: () => void | Promise<void>): void;
  function afterAll<T>(fn: () => void | Promise<void>): void;
  function after<T>(fn: () => void | Promise<void>): void;
  function beforeEach<T>(fn: () => void | Promise<void>): void;
  function afterEach<T>(fn: () => void | Promise<void>): void;
  type DescribeArgs<T> = [DescribeDefinition<T>] | [string] | [string, Omit<DescribeDefinition<T>, "name">] | [string, () => void | undefined] | [() => void | undefined] | [string, Omit<DescribeDefinition<T>, "fn" | "name">, () => void | undefined] | [Omit<DescribeDefinition<T>, "fn">, () => void | undefined] | [Omit<DescribeDefinition<T>, "fn" | "name">, () => void | undefined] | [TestSuite<T>, string] | [TestSuite<T>, string, Omit<DescribeDefinition<T>, "name" | "suite">] | [TestSuite<T>, string, () => void | undefined] | [TestSuite<T>, () => void | undefined] | [TestSuite<T>, string, Omit<DescribeDefinition<T>, "fn" | "name" | "suite">, () => void | undefined] | [TestSuite<T>, Omit<DescribeDefinition<T>, "fn" | "suite">, () => void | undefined] | [TestSuite<T>, Omit<DescribeDefinition<T>, "fn" | "name" | "suite">, () => void | undefined];
  function describe<T>(...args: DescribeArgs<T>): TestSuite<T>;
  export { DescribeDefinition, ItDefinition, TestSuite, ItArgs, it, test, beforeAll, before, afterAll, after, beforeEach, afterEach, DescribeArgs, describe };
}
