import { spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import type { Plugin } from 'esbuild';

let inputHash = await checkUpToDate();
await compileAndVendor();
await Promise.all([fixJsImports(), fixDtsImports()]);
await fixDenoIndexDts();
if (!inputHash) inputHash = await computeInputHash();
await fs.writeFile('./dist/.build-hash', inputHash + '\n');

// Skip the full build when no inputs have changed. Inputs: shims/**/*.ts
// (excl. vendor-types/), tsconfig.json, qunit source, deno.lock, and build.ts.
async function checkUpToDate(): Promise<string> {
  const storedHash = await fs
    .readFile('./dist/.build-hash', 'utf8')
    .then((s) => s.trim())
    .catch(() => null);
  if (storedHash !== null) {
    const hash = await computeInputHash();
    if (await isBuildUpToDate(hash, storedHash)) process.exit(0);
    return hash;
  }
  return '';
}

// Patch and copy vendor files, generate type declarations, and run tsc + esbuild
// all in parallel. qunit.d.ts is written first so tsc can start immediately.
async function compileAndVendor(): Promise<void> {
  const [qunitJS, qunitCSS] = await Promise.all([
    fs.readFile('./node_modules/qunit/qunit/qunit.js'),
    fs.readFile('./node_modules/qunit/qunit/qunit.css'),
    fs.mkdir('./vendor', { recursive: true }),
  ]);

  // Prepend a guard that replaces process.env with a safe empty object when running
  // in Deno without --allow-env. Deno's process.env is a Proxy that throws NotCapable
  // on any key access if the permission is not granted. This single patch covers all
  // process.env reads inside qunit.js regardless of where they appear, so it stays
  // correct across qunit version upgrades without needing to match specific code patterns.
  const denoEnvGuard = `\
;(function () {
  if (typeof process === 'undefined') return;
  try { process.env['']; } catch (_) {
    try { Object.defineProperty(process, 'env', { value: {}, writable: true, configurable: true }); } catch (_) {}
  }
})();
`;

  const newQUnit =
    denoEnvGuard +
    qunitJS.toString().replace(
      'start: function start(count) {',
      `reset: function() {
		ProcessingQueue.finished = false;
		globalStartCalled = false;
		runStarted = false;

		config.queue.length = 0;
		config.modules.length = 0;
		config.autostart = false;

    Object.assign(config.stats, { total: 0, passed: 0, failed: 0, skipped: 0, todo: 0 });

		[
			"started", "updateRate", "filter", "depth", "current",
			"pageLoaded", "timeoutHandler", "timeout", "pollution"
		].forEach( ( key ) => delete config[ key ] );

		const suiteReport = config.currentModule.suiteReport;

		suiteReport.childSuites.length = 0;
		delete suiteReport._startTime;
		delete suiteReport._endTime;

		config.modules.push( config.currentModule );
  },
  start: function start(count) {`,
    );

  // Auto-generated type declarations for the patched QUnit API.
  // Update this template in build.ts when upgrading qunit to a version with API changes.
  const qunitDts = `// Auto-generated by build.ts — do not edit manually.
// Update this template in build.ts when upgrading qunit to a version with API changes.

export interface QUnitConfig {
  autostart: boolean;
  [key: string]: unknown;
}

interface QUnitInstance {
  config: QUnitConfig;
  isLocal: boolean;
  version: string;
  on(event: string, callback: (...args: unknown[]) => void): void;
  test(name: string, callback: (assert: unknown) => void | Promise<void>): void;
  module(name: string, callback: (hooks: unknown) => void): void;
  skip(name: string, callback: (assert: unknown) => void): void;
  todo(name: string, callback: (assert: unknown) => void): void;
  only(name: string, callback: (assert: unknown) => void): void;
  start(count?: number): void;
  /** Added by qunitx's build patch for browser test isolation. */
  reset(): void;
  is(type: string, obj: unknown): boolean;
  extend(target: object, source: object): object;
  stack(offset?: number): string;
  onUnhandledRejection(reason: unknown): void;
  objectType(obj: unknown): string;
  load(): void;
  onError(callback: (...args: unknown[]) => void): void;
  pushFailure(message: string, source?: string, value?: unknown): void;
  equiv(a: unknown, b: unknown): boolean;
  begin(callback: (...args: unknown[]) => void): void;
  log(callback: (...args: unknown[]) => void): void;
  testStart(callback: (...args: unknown[]) => void): void;
  testDone(callback: (...args: unknown[]) => void): void;
  moduleStart(callback: (...args: unknown[]) => void): void;
  moduleDone(callback: (...args: unknown[]) => void): void;
  done(callback: (...args: unknown[]) => void): void;
  diff(a: unknown, b: unknown): string;
  assert: unknown;
  dump: unknown;
  [key: string]: unknown;
}

declare const QUnit: QUnitInstance;
export default QUnit;

declare global {
  var QUnit: QUnitInstance;
}
`;

  // Write qunit.d.ts before spawning tsc so tsc never reads a missing file.
  await fs.writeFile('./vendor/qunit.d.ts', qunitDts);

  await Promise.all([
    fs.writeFile('./vendor/qunit.js', newQUnit),
    fs.writeFile('./vendor/qunit.css', qunitCSS),
    ensureVendorPackageJson(),
    spawnInherit('./node_modules/.bin/tsc', ['--emitDeclarationOnly']),
    // Fast JS emission. After esbuild, overwrite dist/deno/index.js with a fully
    // self-contained bundle (no jsr: imports) so npm:qunitx works in Deno.
    (async () => {
      const shimSources = (
        await findFiles('./shims', (n) => n.endsWith('.ts'), 'vendor-types')
      ).filter((f) => !f.endsWith('.d.ts'));
      await spawnInherit('./node_modules/.bin/esbuild', [
        ...shimSources,
        '--bundle=false',
        '--format=esm',
        '--outbase=shims',
        '--outdir=dist',
      ]);
      await bundleDenoShim();
    })(),
  ]);
}

// Rewrite .ts → .js in relative imports inside esbuild's JS output.
async function fixJsImports(): Promise<void> {
  const jsFiles = await findFiles('./dist', (n) => n.endsWith('.js') && !n.endsWith('.d.ts'));
  await Promise.all(
    jsFiles.map(async (f) => {
      const src = await fs.readFile(f, 'utf8');
      const fixed = src.replace(/(from\s+['"])(\.\.?\/[^'"]*?)\.ts(['"])/g, '$1$2.js$3');
      if (fixed !== src) await fs.writeFile(f, fixed);
    }),
  );
}

// Fix .d.ts files: rewrite relative `.ts` import extensions → `.js`.
// TypeScript's rewriteRelativeImportExtensions only affects .js output,
// not declaration files — so consumers would otherwise see broken .ts paths.
async function fixDtsImports(): Promise<void> {
  const [distDts, vendorDts] = await Promise.all([
    findFiles('./dist', (n) => n.endsWith('.d.ts')),
    findFiles('./vendor', (n) => n.endsWith('.d.ts')),
  ]);
  const dtsSet = new Set([...distDts, ...vendorDts].map((f) => path.resolve(f)));
  await Promise.all(
    distDts.map(async (dtsPath) => {
      const dir = path.dirname(dtsPath);
      const original = await fs.readFile(dtsPath, 'utf8');
      const fixed = original
        // from './foo.ts'  →  from './foo.js'
        .replace(/(from\s+['"])(\.\.?\/[^'"]*?)\.ts(['"])/g, '$1$2.js$3')
        // import("../foo.ts")  →  import("../foo.js")
        .replace(/(import\(['"])(\.\.?\/[^'"]*?)\.ts(['"]\))/g, '$1$2.js$3')
        // from '../foo.d.js'  →  from '../foo.d.ts'  (only when a sibling .d.ts exists)
        // TypeScript 5 Bundler resolution emits `.d.js` in declaration files for imports
        // of other declaration files (e.g. `assert.d.js` for `assert.ts`).  Deno does not
        // follow TypeScript's implicit `.d.js`→`.d.ts` mapping so we rewrite it explicitly.
        // Must run before the general .js→.d.ts pass because `p` in that pass captures
        // `foo.d` (with the stray `.d`), producing a wrong `foo.d.d.ts` lookup.
        .replace(
          /(from\s+['"]|import\(['"])(\.\.?\/[^'"]*?)\.d\.js(['"]\)|['"])/g,
          (match, pre, p, post) =>
            dtsSet.has(path.resolve(dir, p + '.d.ts')) ? `${pre}${p}.d.ts${post}` : match,
        )
        // from './foo.js'  →  from './foo.d.ts'  (only when a sibling .d.ts exists)
        // import('./foo.js')  →  import('./foo.d.ts')  (same, for type import expressions)
        // Deno resolves .js imports in .d.ts files to the actual JS rather than
        // following TypeScript's implicit .js→.d.ts mapping, pulling in node:*
        // imports and requiring @types/node from consumer projects.
        .replace(
          /(from\s+['"]|import\(['"])(\.\.?\/[^'"]*?)\.js(['"]\)|['"])/g,
          (match, pre, p, post) =>
            dtsSet.has(path.resolve(dir, p + '.d.ts')) ? `${pre}${p}.d.ts${post}` : match,
        );
      if (fixed !== original) await fs.writeFile(dtsPath, fixed);
    }),
  );
}

// Strip the jsr:@std/assert import from dist/deno/index.d.ts so consumers can
// type-check without having jsr:@std/assert pre-cached. The runtime bundle already
// has all jsr: code inlined. Declaring AssertionError as `extends Error` is accurate
// and removes the external dependency entirely.
async function fixDenoIndexDts(): Promise<void> {
  const dtsPath = './dist/deno/index.d.ts';
  const src = await fs.readFile(dtsPath, 'utf8');
  const fixed = src
    .replace('import { AssertionError as DenoAssertionError } from "jsr:@std/assert";\n', '')
    .replace('extends DenoAssertionError', 'extends Error');
  if (fixed !== src) await fs.writeFile(dtsPath, fixed);
}

async function ensureVendorPackageJson(): Promise<void> {
  await fs
    .writeFile(
      './vendor/package.json',
      JSON.stringify({ name: 'qunitx-vendor', version: '0.0.1' }),
      { flag: 'wx' },
    )
    .catch((err: { code?: string }) => {
      if (err.code !== 'EEXIST') throw err;
    });
}

// Produces dist/deno/index.js with all jsr: imports inlined.
// When Deno loads npm:qunitx it uses Node's ESM loader, which cannot resolve
// jsr: URL schemes. We use esbuild's JS API with a custom plugin that fetches
// jsr: packages from https://jsr.io and inlines them, producing a single
// self-contained module.
async function bundleDenoShim(): Promise<void> {
  // Parse deno.lock to map each jsr package name → resolved version.
  const lockText = await fs.readFile('./deno.lock', 'utf8');
  const lock = JSON.parse(lockText) as { specifiers?: Record<string, string> };
  const jsrVersions = new Map<string, string>();
  for (const [spec, version] of Object.entries(lock.specifiers ?? {})) {
    const m = spec.match(/^jsr:(@[^@]+)@/);
    // Keep first match per package (entries are ordered, first is sufficient).
    if (m && !jsrVersions.has(m[1]!)) jsrVersions.set(m[1]!, version);
  }

  const fetchTextCache = new Map<string, string>();
  async function fetchText(url: string): Promise<string> {
    const cached = fetchTextCache.get(url);
    if (cached !== undefined) return cached;
    const resp = await fetch(url);
    if (!resp.ok) throw new Error(`fetch ${url} → ${resp.status} ${resp.statusText}`);
    const text = await resp.text();
    fetchTextCache.set(url, text);
    return text;
  }

  // Fetch a package's deno.json exports map and cache it.
  // jsr:@std/internal@^1.0.12/assertion-state → look up "./assertion-state" in exports
  const exportsCache = new Map<string, Record<string, string>>();
  async function getExports(pkg: string, version: string): Promise<Record<string, string>> {
    const key = `${pkg}@${version}`;
    const cached = exportsCache.get(key);
    if (cached !== undefined) return cached;
    const url = `https://jsr.io/${pkg}/${version}/deno.json`;
    const resp = await fetch(url);
    const exports = resp.ok
      ? (((await resp.json()) as { exports?: Record<string, string> }).exports ?? {})
      : {};
    exportsCache.set(key, exports);
    return exports;
  }

  // Convert a jsr: specifier to a concrete https://jsr.io URL.
  // Root:    "jsr:@std/assert"                          → .../mod.ts  (via exports["."])
  // Subpath: "jsr:@std/testing/bdd"                     → via exports["./bdd"]
  // Pinned:  "jsr:@std/internal@^1.0.12/assertion-state"→ via exports["./assertion-state"]
  async function jsrToUrl(specifier: string): Promise<string> {
    // Capture: @scope/name, optional @version-constraint, optional /subpath
    const m = specifier.match(/^jsr:(@[^/@]+\/[^/@]+)(?:@[^/]+)?(\/.*)?$/);
    if (!m) throw new Error(`Unparseable jsr: specifier: ${specifier}`);
    const pkg = m[1]!;
    const sub = m[2] ?? '';
    const version = jsrVersions.get(pkg);
    if (!version) throw new Error(`${pkg} not found in deno.lock`);
    const exports = await getExports(pkg, version);
    const exportKey = sub ? `.${sub}` : '.';
    const file = exports[exportKey];
    if (!file)
      throw new Error(
        `No export "${exportKey}" in ${pkg}@${version} (keys: ${Object.keys(exports).join(', ')})`,
      );
    // file is like "./mod.ts" or "./_assertion_state.ts" — strip leading "."
    return `https://jsr.io/${pkg}/${version}${file.slice(1)}`;
  }

  const jsrPlugin: Plugin = {
    name: 'jsr',
    setup(build) {
      // jsr: imports from local TypeScript files → resolve to https://jsr.io
      build.onResolve({ filter: /^jsr:/ }, async (args) => ({
        path: await jsrToUrl(args.path),
        namespace: 'jsr',
      }));
      // relative imports inside fetched jsr modules → resolve relative to their importer URL
      build.onResolve({ filter: /^\./, namespace: 'jsr' }, (args) => ({
        path: new URL(args.path, args.importer).toString(),
        namespace: 'jsr',
      }));
      // load any jsr-namespaced path by fetching its TypeScript source
      build.onLoad({ filter: /.*/, namespace: 'jsr' }, async (args) => ({
        contents: await fetchText(args.path),
        loader: 'ts',
      }));

      // vendor/qunit.js is a UMD module.  When esbuild bundles it as CJS the UMD
      // code takes the `module.exports = QUnit` branch (exportedModule=true), so
      // the `globalThis.QUnit = QUnit` fallback never runs.  The shim reads
      // `Assert.QUnit` from `globalThis.QUnit` — fix by appending an explicit setter
      // to the source before esbuild wraps it, so it runs inside the CJS closure
      // where `exports` is defined and equals the QUnit object.
      build.onLoad({ filter: /[/\\]vendor[/\\]qunit\.js$/ }, async (args) => {
        const src = await fs.readFile(args.path, 'utf8');
        return {
          contents:
            src +
            '\nif (typeof exports !== "undefined" && exports.QUnit && typeof globalThis !== "undefined") { globalThis.QUnit = exports.QUnit; }',
          loader: 'js',
        };
      });
    },
  };

  const esbuild = await import('esbuild');
  try {
    await esbuild.build({
      plugins: [jsrPlugin],
      entryPoints: ['./shims/deno/index.ts'],
      outfile: './dist/deno/index.js',
      bundle: true,
      format: 'esm',
      platform: 'neutral',
      // Tell Deno where to find the type declarations for this bundle.
      // Without this, Deno treats the file as untyped JavaScript when imported
      // via an import-map entry that points directly into node_modules, because
      // it does not check for a co-located .d.ts in that case.
      banner: { js: '// @ts-types="./index.d.ts"' },
    });
  } finally {
    await esbuild.stop();
  }
}

function spawnInherit(cmd: string, args: string[]): Promise<void> {
  return new Promise((resolve, reject) => {
    const proc = spawn(cmd, args, { stdio: 'inherit' });
    proc.on('close', (code) =>
      code === 0 ? resolve() : reject(new Error(`${cmd} exited with code ${code}`)),
    );
  });
}

// Generic recursive file finder. Skips directories named `excludeDir` when set.
async function findFiles(
  dir: string,
  match: (name: string) => boolean,
  excludeDir?: string,
): Promise<string[]> {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const results = await Promise.all(
    entries.map((e) => {
      const full = `${dir}/${e.name}`;
      if (e.isDirectory())
        return excludeDir && e.name === excludeDir ? [] : findFiles(full, match, excludeDir);
      return match(e.name) ? [full] : [];
    }),
  );
  return results.flat();
}

async function computeInputHash(): Promise<string> {
  const hash = createHash('sha1');
  const [shimFiles, tsconfig, qunitSrc, denoLock, buildSelf] = await Promise.all([
    findFiles('./shims', (n) => n.endsWith('.ts'), 'vendor-types'),
    fs.readFile('./tsconfig.json').catch(() => Buffer.from('')),
    fs.readFile('./node_modules/qunit/qunit/qunit.js').catch(() => Buffer.from('')),
    fs.readFile('./deno.lock').catch(() => Buffer.from('')),
    fs.readFile('./build.ts').catch(() => Buffer.from('')),
  ]);
  hash.update(tsconfig);
  hash.update(qunitSrc);
  hash.update(denoLock);
  hash.update(buildSelf);
  const sortedFiles = shimFiles.sort();
  const fileContents = await Promise.all(sortedFiles.map((f) => fs.readFile(f)));
  for (let i = 0; i < sortedFiles.length; i++) {
    hash.update(sortedFiles[i]!);
    hash.update(fileContents[i]!);
  }
  return hash.digest('hex');
}

async function isBuildUpToDate(currentHash: string, storedHash: string): Promise<boolean> {
  try {
    await Promise.all([
      fs.stat('./dist/browser/index.js'),
      fs.stat('./dist/deno/index.js'),
      fs.stat('./dist/node/index.js'),
    ]);
    return storedHash === currentHash;
  } catch {
    return false;
  }
}
